# Generated by Django 5.0.6 on 2024-06-16 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnisocialnetworkapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="assigned_groups",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="assigned_events",
                to="alumnisocialnetworkapi.group",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="group_notification",
            field=models.ManyToManyField(
                null=True,
                related_name="group_notifications",
                to="alumnisocialnetworkapi.group",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user_notification",
            field=models.ManyToManyField(
                null=True,
                related_name="user_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
