# Generated by Django 3.2 on 2024-06-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnisocialnetworkapi', '0003_alter_notification_group_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
